"""
Curated lead list of 100 AI companies for anime/esports training data outreach.
US-focused with select international legendary fits.
Ready for import into Attio CRM and Apollo enrichment.
"""

import csv
from pathlib import Path

# 100 Curated AI Companies (US-focused)
LEAD_LIST = [
    # === IMAGE GENERATION (16) ===
    {
        "company": "Stability AI",
        "website": "https://stability.ai",
        "linkedin": "https://linkedin.com/company/stability-ai",
        "category": "Image Generation",
        "relevance": "Stable Diffusion - MASSIVE anime community, thousands of fine-tuned models",
        "funding_stage": "Series B",
        "country": "UK",
        "priority": "HIGH",
        "notes": "LEGENDARY FIT - Anime is core to their community",
    },
    {
        "company": "Midjourney",
        "website": "https://midjourney.com",
        "linkedin": "https://linkedin.com/company/midjourney",
        "category": "Image Generation",
        "relevance": "Niji mode specifically for anime, huge art community",
        "funding_stage": "Self-funded",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Leonardo.AI",
        "website": "https://leonardo.ai",
        "linkedin": "https://linkedin.com/company/leonardo-ai",
        "category": "Image Generation",
        "relevance": "Game art generation, anime-style models, gaming focus",
        "funding_stage": "Series A",
        "country": "Australia",
        "priority": "HIGH",
        "notes": "LEGENDARY FIT - Built for game dev, strong anime models",
    },
    {
        "company": "Civitai",
        "website": "https://civitai.com",
        "linkedin": "https://linkedin.com/company/civitai",
        "category": "Image Generation",
        "relevance": "Largest anime AI model community, model sharing platform",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "HIGH",
        "notes": "LEGENDARY FIT - Anime is 70%+ of their content",
    },
    {
        "company": "NovelAI",
        "website": "https://novelai.net",
        "linkedin": "",
        "category": "Image Generation",
        "relevance": "Anime-first image generation, trained on anime data",
        "funding_stage": "Unknown",
        "country": "US",
        "priority": "HIGH",
        "notes": "LEGENDARY FIT - Anime-specific product",
    },
    {
        "company": "PixAI",
        "website": "https://pixai.art",
        "linkedin": "",
        "category": "Image Generation",
        "relevance": "Anime-specific AI art generator",
        "funding_stage": "Unknown",
        "country": "US",
        "priority": "HIGH",
        "notes": "LEGENDARY FIT - 100% anime focused",
    },
    {
        "company": "Holara AI",
        "website": "https://holara.ai",
        "linkedin": "",
        "category": "Image Generation",
        "relevance": "Anime art generation specialist",
        "funding_stage": "Unknown",
        "country": "US",
        "priority": "HIGH",
        "notes": "LEGENDARY FIT - Anime-only product",
    },
    {
        "company": "Ideogram",
        "website": "https://ideogram.ai",
        "linkedin": "https://linkedin.com/company/ideogram-ai",
        "category": "Image Generation",
        "relevance": "Text rendering in images, creative generation",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Artbreeder",
        "website": "https://artbreeder.com",
        "linkedin": "https://linkedin.com/company/artbreeder",
        "category": "Image Generation",
        "relevance": "Collaborative AI art, character portraits",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Invoke AI",
        "website": "https://invoke.com",
        "linkedin": "https://linkedin.com/company/invoke-ai",
        "category": "Image Generation",
        "relevance": "Open-source Stable Diffusion tools, acquired by Adobe",
        "funding_stage": "Acquired",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Krea AI",
        "website": "https://krea.ai",
        "linkedin": "https://linkedin.com/company/krea-ai",
        "category": "Image Generation",
        "relevance": "Real-time AI generation, creative tools",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Playground AI",
        "website": "https://playground.com",
        "linkedin": "https://linkedin.com/company/playgroundai",
        "category": "Image Generation",
        "relevance": "Free AI image generation platform",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "OpenAI",
        "website": "https://openai.com",
        "linkedin": "https://linkedin.com/company/openai",
        "category": "Image Generation",
        "relevance": "DALL-E, Sora video - visual generation at scale",
        "funding_stage": "Growth",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Adobe Firefly",
        "website": "https://adobe.com/products/firefly",
        "linkedin": "https://linkedin.com/company/adobe",
        "category": "Image Generation",
        "relevance": "Enterprise image generation, creative cloud integration",
        "funding_stage": "Public",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Black Forest Labs",
        "website": "https://blackforestlabs.ai",
        "linkedin": "https://linkedin.com/company/black-forest-labs",
        "category": "Image Generation",
        "relevance": "FLUX models, ex-Stability team, state-of-art image gen",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Recraft AI",
        "website": "https://recraft.ai",
        "linkedin": "https://linkedin.com/company/recraft-ai",
        "category": "Image Generation",
        "relevance": "Vector and design-focused image generation",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },

    # === VIDEO GENERATION (12) ===
    {
        "company": "Runway",
        "website": "https://runwayml.com",
        "linkedin": "https://linkedin.com/company/runwayml",
        "category": "Video Generation",
        "relevance": "Gen-3 video, animation capabilities, Lionsgate partnership",
        "funding_stage": "Series D ($544M)",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Pika Labs",
        "website": "https://pika.art",
        "linkedin": "https://linkedin.com/company/pika-labs",
        "category": "Video Generation",
        "relevance": "Video generation from images/text, popular for anime clips",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Luma AI",
        "website": "https://lumalabs.ai",
        "linkedin": "https://linkedin.com/company/luma-ai",
        "category": "Video Generation",
        "relevance": "Dream Machine video generation, 3D capture",
        "funding_stage": "Series B",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "HeyGen",
        "website": "https://heygen.com",
        "linkedin": "https://linkedin.com/company/heygen",
        "category": "Video Generation",
        "relevance": "AI avatar video generation",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Hedra",
        "website": "https://hedra.com",
        "linkedin": "https://linkedin.com/company/hedra-ai",
        "category": "Video Generation",
        "relevance": "Character dialogue videos, $32M from A16z",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Captions",
        "website": "https://captions.ai",
        "linkedin": "https://linkedin.com/company/captions-ai",
        "category": "Video Generation",
        "relevance": "AI video editing, avatars for creators",
        "funding_stage": "Series C ($100M)",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Genmo",
        "website": "https://genmo.ai",
        "linkedin": "https://linkedin.com/company/genmo-ai",
        "category": "Video Generation",
        "relevance": "AI video/3D generation, Mochi model",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Kaiber",
        "website": "https://kaiber.ai",
        "linkedin": "https://linkedin.com/company/kaiber-ai",
        "category": "Video Generation",
        "relevance": "AI video generation for music/creators, anime styles popular",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Opus Clip",
        "website": "https://opus.pro",
        "linkedin": "https://linkedin.com/company/opus-clip",
        "category": "Video Generation",
        "relevance": "AI video repurposing, gaming content focus",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "HIGH",
        "notes": "Strong gaming/esports creator market",
    },
    {
        "company": "Twelve Labs",
        "website": "https://twelvelabs.io",
        "linkedin": "https://linkedin.com/company/twelve-labs",
        "category": "Video Generation",
        "relevance": "Video understanding AI, could use labeled video data",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Descript",
        "website": "https://descript.com",
        "linkedin": "https://linkedin.com/company/descript",
        "category": "Video Generation",
        "relevance": "AI video/audio editing, Overdub voice cloning",
        "funding_stage": "Series C ($100M)",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Kapwing",
        "website": "https://kapwing.com",
        "linkedin": "https://linkedin.com/company/kapwing",
        "category": "Video Generation",
        "relevance": "Video editing with AI, popular with gaming creators",
        "funding_stage": "Series B",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },

    # === GAMING AI (16) ===
    {
        "company": "Inworld AI",
        "website": "https://inworld.ai",
        "linkedin": "https://linkedin.com/company/inworld-ai",
        "category": "Gaming AI",
        "relevance": "NPC AI, Xbox/Microsoft partnership, character engine",
        "funding_stage": "Series A ($60M)",
        "country": "US",
        "priority": "HIGH",
        "notes": "LEGENDARY FIT - Building game characters",
    },
    {
        "company": "Convai",
        "website": "https://convai.com",
        "linkedin": "https://linkedin.com/company/convai",
        "category": "Gaming AI",
        "relevance": "Game character AI conversations, NPC dialogue",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Scenario",
        "website": "https://scenario.com",
        "linkedin": "https://linkedin.com/company/scenario-gg",
        "category": "Gaming AI",
        "relevance": "AI game asset generation, consistent style training",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "HIGH",
        "notes": "LEGENDARY FIT - Game art is core product",
    },
    {
        "company": "Sett",
        "website": "https://sett.gg",
        "linkedin": "https://linkedin.com/company/sett-ai",
        "category": "Gaming AI",
        "relevance": "AI agents for mobile game dev, $27M funding",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Layer AI",
        "website": "https://layer.ai",
        "linkedin": "https://linkedin.com/company/layer-ai",
        "category": "Gaming AI",
        "relevance": "AI game asset creation platform",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Latitude (AI Dungeon)",
        "website": "https://latitude.io",
        "linkedin": "https://linkedin.com/company/latitude-io",
        "category": "Gaming AI",
        "relevance": "AI-powered interactive storytelling, anime scenarios popular",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Promethean AI",
        "website": "https://prometheanai.com",
        "linkedin": "https://linkedin.com/company/promethean-ai",
        "category": "Gaming AI",
        "relevance": "AI virtual world creation for AAA games",
        "funding_stage": "Seed ($3.5M)",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Sortium",
        "website": "https://sortium.com",
        "linkedin": "https://linkedin.com/company/sortium",
        "category": "Gaming AI",
        "relevance": "Real-time 3D asset generation via prompts",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Meshy",
        "website": "https://meshy.ai",
        "linkedin": "https://linkedin.com/company/meshy-ai",
        "category": "Gaming AI",
        "relevance": "3D model generation from text/images, game ready",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Ponzu",
        "website": "https://ponzu.ai",
        "linkedin": "",
        "category": "Gaming AI",
        "relevance": "AI texturing for 3D assets, anime styles",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Opus",
        "website": "https://opus.ai",
        "linkedin": "https://linkedin.com/company/opus-ai",
        "category": "Gaming AI",
        "relevance": "Generative AI world building",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Spline",
        "website": "https://spline.design",
        "linkedin": "https://linkedin.com/company/splonetool",
        "category": "Gaming AI",
        "relevance": "3D design with AI generation",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Roblox",
        "website": "https://roblox.com",
        "linkedin": "https://linkedin.com/company/roblox",
        "category": "Gaming AI",
        "relevance": "AI game creation tools, massive platform",
        "funding_stage": "Public",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Unity",
        "website": "https://unity.com",
        "linkedin": "https://linkedin.com/company/unity-technologies",
        "category": "Gaming AI",
        "relevance": "Game engine with AI tools, Muse AI",
        "funding_stage": "Public",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Epic Games",
        "website": "https://epicgames.com",
        "linkedin": "https://linkedin.com/company/epic-games",
        "category": "Gaming AI",
        "relevance": "Unreal Engine AI tools, MetaHuman",
        "funding_stage": "Growth",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Didimo",
        "website": "https://didimo.co",
        "linkedin": "https://linkedin.com/company/didimo",
        "category": "Gaming AI",
        "relevance": "AI digital human creation for games",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },

    # === ANIMATION AI (10) ===
    {
        "company": "Cartwheel",
        "website": "https://cartwheel.com",
        "linkedin": "https://linkedin.com/company/cartwheel-ai",
        "category": "Animation AI",
        "relevance": "3D character animation, Pixar/DreamWorks users",
        "funding_stage": "Seed ($15.6M)",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Cheehoo",
        "website": "https://cheehoo.ai",
        "linkedin": "https://linkedin.com/company/cheehoo-ai",
        "category": "Animation AI",
        "relevance": "Animation AI from ex-DreamWorks/Rideback team",
        "funding_stage": "Seed ($10M)",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Animation Inc.",
        "website": "https://animation.inc",
        "linkedin": "https://linkedin.com/company/animation-inc",
        "category": "Animation AI",
        "relevance": "Real-time generative animation, ex-Meta team",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Wonder Dynamics",
        "website": "https://wonderdynamics.com",
        "linkedin": "https://linkedin.com/company/wonder-dynamics",
        "category": "Animation AI",
        "relevance": "AI-powered VFX and character animation",
        "funding_stage": "Acquired by Autodesk",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "DeepMotion",
        "website": "https://deepmotion.com",
        "linkedin": "https://linkedin.com/company/deepmotion",
        "category": "Animation AI",
        "relevance": "AI body tracking and animation",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "RADiCAL",
        "website": "https://radical.app",
        "linkedin": "https://linkedin.com/company/radical-motion",
        "category": "Animation AI",
        "relevance": "AI motion capture from video",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Move AI",
        "website": "https://move.ai",
        "linkedin": "https://linkedin.com/company/move-ai",
        "category": "Animation AI",
        "relevance": "Markerless motion capture AI",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Plask",
        "website": "https://plask.ai",
        "linkedin": "https://linkedin.com/company/plask-ai",
        "category": "Animation AI",
        "relevance": "AI motion capture from video, anime/game animation",
        "funding_stage": "Series A",
        "country": "South Korea",
        "priority": "HIGH",
        "notes": "LEGENDARY FIT - Korea is anime/gaming hub",
    },
    {
        "company": "Cascadeur",
        "website": "https://cascadeur.com",
        "linkedin": "https://linkedin.com/company/cascadeur",
        "category": "Animation AI",
        "relevance": "AI-assisted animation for games",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Rokoko",
        "website": "https://rokoko.com",
        "linkedin": "https://linkedin.com/company/rokoko-electronics",
        "category": "Animation AI",
        "relevance": "Motion capture with AI, Vision for video mocap",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "HQ moved to US",
    },

    # === CHARACTER/AVATAR AI (12) ===
    {
        "company": "Character.AI",
        "website": "https://character.ai",
        "linkedin": "https://linkedin.com/company/character-ai",
        "category": "Character AI",
        "relevance": "AI characters - massive anime character community",
        "funding_stage": "Series A ($150M)",
        "country": "US",
        "priority": "HIGH",
        "notes": "LEGENDARY FIT - Anime characters are huge on platform",
    },
    {
        "company": "Lemon Slice",
        "website": "https://lemonslice.ai",
        "linkedin": "https://linkedin.com/company/lemon-slice-ai",
        "category": "Character AI",
        "relevance": "Real-time AI avatars, $10.5M from YC/Matrix",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "AvatarOS",
        "website": "https://avataros.ai",
        "linkedin": "https://linkedin.com/company/avataros",
        "category": "Character AI",
        "relevance": "Virtual influencer platform, Lil Miquela creator",
        "funding_stage": "Seed ($7M)",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Hologram Labs",
        "website": "https://hologramlabs.com",
        "linkedin": "https://linkedin.com/company/hologram-labs",
        "category": "Character AI",
        "relevance": "AI for vtubers and digital celebrities",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "HIGH",
        "notes": "LEGENDARY FIT - VTuber is anime culture",
    },
    {
        "company": "Genies",
        "website": "https://genies.com",
        "linkedin": "https://linkedin.com/company/genaborhood",
        "category": "Character AI",
        "relevance": "AI avatar creation, celebrity partnerships",
        "funding_stage": "Series C",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Ready Player Me",
        "website": "https://readyplayer.me",
        "linkedin": "https://linkedin.com/company/wolf3d",
        "category": "Character AI",
        "relevance": "Cross-game avatar platform, 9000+ apps",
        "funding_stage": "Series B",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "US operations",
    },
    {
        "company": "IMVU",
        "website": "https://imvu.com",
        "linkedin": "https://linkedin.com/company/imvu",
        "category": "Character AI",
        "relevance": "Avatar social platform, anime styles popular",
        "funding_stage": "Growth",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Krikey AI",
        "website": "https://krikey.ai",
        "linkedin": "https://linkedin.com/company/krikey",
        "category": "Character AI",
        "relevance": "AI avatar animation from text",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Pinscreen",
        "website": "https://pinscreen.com",
        "linkedin": "https://linkedin.com/company/pinscreen",
        "category": "Character AI",
        "relevance": "AI avatars and digital humans",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Brud",
        "website": "https://bfrnd.world",
        "linkedin": "https://linkedin.com/company/brud",
        "category": "Character AI",
        "relevance": "Virtual characters/influencers (Lil Miquela)",
        "funding_stage": "Series B",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Hour One",
        "website": "https://hourone.ai",
        "linkedin": "https://linkedin.com/company/hourone",
        "category": "Character AI",
        "relevance": "AI video avatars and presenters",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Colossyan",
        "website": "https://colossyan.com",
        "linkedin": "https://linkedin.com/company/colossyan",
        "category": "Character AI",
        "relevance": "AI video avatars for enterprise",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },

    # === VOICE AI (8) ===
    {
        "company": "ElevenLabs",
        "website": "https://elevenlabs.io",
        "linkedin": "https://linkedin.com/company/elevenlabsio",
        "category": "Voice AI",
        "relevance": "Voice synthesis, dubbing - anime dubbing use case",
        "funding_stage": "Series C ($180M)",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Resemble AI",
        "website": "https://resemble.ai",
        "linkedin": "https://linkedin.com/company/resembleai",
        "category": "Voice AI",
        "relevance": "Voice cloning for games and content",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Replica Studios",
        "website": "https://replicastudios.com",
        "linkedin": "https://linkedin.com/company/replica-studios",
        "category": "Voice AI",
        "relevance": "AI voices specifically for games, Unity/Unreal plugins",
        "funding_stage": "Series A",
        "country": "Australia",
        "priority": "HIGH",
        "notes": "LEGENDARY FIT - Game voice focus",
    },
    {
        "company": "Suno",
        "website": "https://suno.ai",
        "linkedin": "https://linkedin.com/company/suno-ai",
        "category": "Voice AI",
        "relevance": "AI music generation, game/anime soundtracks potential",
        "funding_stage": "Series B ($125M)",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Udio",
        "website": "https://udio.com",
        "linkedin": "https://linkedin.com/company/udio-ai",
        "category": "Voice AI",
        "relevance": "AI music generation",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "WellSaid Labs",
        "website": "https://wellsaidlabs.com",
        "linkedin": "https://linkedin.com/company/wellsaid-labs",
        "category": "Voice AI",
        "relevance": "Enterprise AI voice platform",
        "funding_stage": "Series B",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Murf AI",
        "website": "https://murf.ai",
        "linkedin": "https://linkedin.com/company/murf-ai",
        "category": "Voice AI",
        "relevance": "Text-to-speech for creators",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Play.ht",
        "website": "https://play.ht",
        "linkedin": "https://linkedin.com/company/play-ht",
        "category": "Voice AI",
        "relevance": "AI voice generation platform",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },

    # === TRAINING DATA (10) ===
    {
        "company": "Scale AI",
        "website": "https://scale.com",
        "linkedin": "https://linkedin.com/company/scale-ai",
        "category": "Training Data",
        "relevance": "Training data platform, $7.3B valuation",
        "funding_stage": "Series E",
        "country": "US",
        "priority": "HIGH",
        "notes": "Could be partner or competitor",
    },
    {
        "company": "Labelbox",
        "website": "https://labelbox.com",
        "linkedin": "https://linkedin.com/company/labelbox",
        "category": "Training Data",
        "relevance": "Data labeling platform",
        "funding_stage": "Series D",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Gretel AI",
        "website": "https://gretel.ai",
        "linkedin": "https://linkedin.com/company/gretel-ai",
        "category": "Training Data",
        "relevance": "Synthetic data generation",
        "funding_stage": "Series B ($65M)",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Synthesis AI",
        "website": "https://synthesis.ai",
        "linkedin": "https://linkedin.com/company/synthesisai",
        "category": "Training Data",
        "relevance": "Synthetic data for computer vision - face/body data",
        "funding_stage": "Series B ($30M)",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Parallel Domain",
        "website": "https://paralleldomain.com",
        "linkedin": "https://linkedin.com/company/parallel-domain",
        "category": "Training Data",
        "relevance": "Synthetic data for perception AI",
        "funding_stage": "Series A ($22.5M)",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Surge AI",
        "website": "https://surgehq.ai",
        "linkedin": "https://linkedin.com/company/surge-ai",
        "category": "Training Data",
        "relevance": "High-quality AI training data",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Sama",
        "website": "https://sama.com",
        "linkedin": "https://linkedin.com/company/sama",
        "category": "Training Data",
        "relevance": "AI training data annotation",
        "funding_stage": "Series C",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Defined.ai",
        "website": "https://defined.ai",
        "linkedin": "https://linkedin.com/company/defined-ai",
        "category": "Training Data",
        "relevance": "AI data marketplace",
        "funding_stage": "Series B",
        "country": "US",
        "priority": "HIGH",
        "notes": "Potential distribution partner",
    },
    {
        "company": "Roboflow",
        "website": "https://roboflow.com",
        "linkedin": "https://linkedin.com/company/roboflow-ai",
        "category": "Training Data",
        "relevance": "Computer vision data and training",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "V7 Labs",
        "website": "https://v7labs.com",
        "linkedin": "https://linkedin.com/company/v7labs",
        "category": "Training Data",
        "relevance": "AI training data platform",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },

    # === CREATIVE TOOLS (6) ===
    {
        "company": "Luma Labs",
        "website": "https://lumalabs.ai",
        "linkedin": "https://linkedin.com/company/luma-ai",
        "category": "Creative Tools",
        "relevance": "3D capture and generation, Genie 3D model",
        "funding_stage": "Series B",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Topaz Labs",
        "website": "https://topazlabs.com",
        "linkedin": "https://linkedin.com/company/topaz-labs",
        "category": "Creative Tools",
        "relevance": "AI image/video enhancement, anime upscaling popular",
        "funding_stage": "Bootstrapped",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Magnific AI",
        "website": "https://magnific.ai",
        "linkedin": "https://linkedin.com/company/magnific-ai",
        "category": "Creative Tools",
        "relevance": "AI image upscaling - massive anime community use",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
        "notes": "Strong anime user base",
    },
    {
        "company": "Anthropic",
        "website": "https://anthropic.com",
        "linkedin": "https://linkedin.com/company/anthropic",
        "category": "Creative Tools",
        "relevance": "Claude - multimodal, could expand to image training",
        "funding_stage": "Series C+",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Together AI",
        "website": "https://together.ai",
        "linkedin": "https://linkedin.com/company/together-ai",
        "category": "Creative Tools",
        "relevance": "Model hosting and fine-tuning, custom training",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Hugging Face",
        "website": "https://huggingface.co",
        "linkedin": "https://linkedin.com/company/huggingface",
        "category": "Creative Tools",
        "relevance": "Model hub, datasets - anime models popular",
        "funding_stage": "Series D",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },

    # === ADDITIONAL HIGH-FIT COMPANIES (10) ===
    {
        "company": "Mage.Space",
        "website": "https://mage.space",
        "linkedin": "https://linkedin.com/company/mage-space",
        "category": "Image Generation",
        "relevance": "Free AI art generator, anime models available",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Hotpot.ai",
        "website": "https://hotpot.ai",
        "linkedin": "https://linkedin.com/company/hotpot-ai",
        "category": "Image Generation",
        "relevance": "AI art tools, anime art generator",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Neverai",
        "website": "https://never.ai",
        "linkedin": "https://linkedin.com/company/neverai",
        "category": "Image Generation",
        "relevance": "AI art platform with anime focus",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Esports Engine",
        "website": "https://esportsengine.com",
        "linkedin": "https://linkedin.com/company/esports-engine",
        "category": "Gaming AI",
        "relevance": "Esports production and tech, AI tools",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "HIGH",
        "notes": "Direct esports connection",
    },
    {
        "company": "Blitz.gg",
        "website": "https://blitz.gg",
        "linkedin": "https://linkedin.com/company/blitz-esports",
        "category": "Gaming AI",
        "relevance": "Esports AI assistant, League of Legends focus",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "HIGH",
        "notes": "Direct esports connection",
    },
    {
        "company": "Mobalytics",
        "website": "https://mobalytics.gg",
        "linkedin": "https://linkedin.com/company/mobalytics",
        "category": "Gaming AI",
        "relevance": "Gaming AI analytics, esports coaching",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "HIGH",
        "notes": "Direct esports connection",
    },
    {
        "company": "Fable Studio",
        "website": "https://fable-studio.com",
        "linkedin": "https://linkedin.com/company/fable-studio",
        "category": "Character AI",
        "relevance": "AI virtual beings, interactive characters",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "HIGH",
        "notes": "",
    },
    {
        "company": "Wonder Dynamics",
        "website": "https://wonderdynamics.com",
        "linkedin": "https://linkedin.com/company/wonder-dynamics",
        "category": "Creative Tools",
        "relevance": "Wonder Studio - AI VFX for character replacement",
        "funding_stage": "Acquired by Autodesk",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Flawless AI",
        "website": "https://flawlessai.com",
        "linkedin": "https://linkedin.com/company/flawless-ai",
        "category": "Video Generation",
        "relevance": "AI for film/video, facial performance",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
    {
        "company": "Metaphysic",
        "website": "https://metaphysic.ai",
        "linkedin": "https://linkedin.com/company/metaphysic-ai",
        "category": "Video Generation",
        "relevance": "AI face/body generation for video",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
        "notes": "",
    },
]


def generate_csv(output_path: str = "output/ai_companies_lead_list.csv"):
    """Generate CSV file for Attio/Apollo import."""
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)

    fieldnames = [
        "company",
        "website",
        "linkedin",
        "category",
        "relevance",
        "funding_stage",
        "country",
        "priority",
        "notes",
    ]

    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(LEAD_LIST)

    print(f"Generated {len(LEAD_LIST)} companies to {output_path}")
    return output_path


def get_high_priority():
    """Get HIGH priority leads only."""
    return [c for c in LEAD_LIST if c["priority"] == "HIGH"]


def get_by_category(category: str):
    """Filter by category."""
    return [c for c in LEAD_LIST if c["category"] == category]


def get_legendary_fits():
    """Get companies marked as LEGENDARY FIT."""
    return [c for c in LEAD_LIST if "LEGENDARY" in c.get("notes", "")]


def summary():
    """Print summary of the lead list."""
    print(f"\n{'='*60}")
    print("AI COMPANIES LEAD LIST SUMMARY")
    print(f"{'='*60}")
    print(f"Total companies: {len(LEAD_LIST)}")

    # By priority
    high = len([c for c in LEAD_LIST if c["priority"] == "HIGH"])
    med = len([c for c in LEAD_LIST if c["priority"] == "MEDIUM"])
    print(f"\nBy Priority:")
    print(f"  HIGH:   {high}")
    print(f"  MEDIUM: {med}")

    # By category
    categories = {}
    for c in LEAD_LIST:
        cat = c["category"]
        categories[cat] = categories.get(cat, 0) + 1

    print(f"\nBy Category:")
    for cat, count in sorted(categories.items(), key=lambda x: -x[1]):
        print(f"  {cat}: {count}")

    # By country
    countries = {}
    for c in LEAD_LIST:
        country = c["country"]
        countries[country] = countries.get(country, 0) + 1

    print(f"\nBy Country:")
    for country, count in sorted(countries.items(), key=lambda x: -x[1]):
        print(f"  {country}: {count}")

    # Legendary fits
    legendary = [c for c in LEAD_LIST if "LEGENDARY" in c.get("notes", "")]
    print(f"\nLegendary Fits: {len(legendary)}")
    for c in legendary:
        print(f"  - {c['company']} ({c['country']})")


if __name__ == "__main__":
    summary()
    generate_csv()
