"""
Curated lead list of 100 AI companies for anime/esports training data outreach.
Ready for import into Attio CRM and Apollo enrichment.
"""

import csv
from pathlib import Path

# 100 Curated AI Companies
LEAD_LIST = [
    # === IMAGE GENERATION (15) ===
    {
        "company": "Stability AI",
        "website": "https://stability.ai",
        "linkedin": "https://linkedin.com/company/stability-ai",
        "category": "Image Generation",
        "relevance": "Stable Diffusion - huge anime community, fine-tuned models",
        "funding_stage": "Series B",
        "country": "UK",
        "priority": "HIGH",
    },
    {
        "company": "Midjourney",
        "website": "https://midjourney.com",
        "linkedin": "https://linkedin.com/company/midjourney",
        "category": "Image Generation",
        "relevance": "Popular for anime/art styles, niji mode",
        "funding_stage": "Self-funded",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Leonardo.AI",
        "website": "https://leonardo.ai",
        "linkedin": "https://linkedin.com/company/leonardo-ai",
        "category": "Image Generation",
        "relevance": "Game art generation, anime-style models",
        "funding_stage": "Series A",
        "country": "Australia",
        "priority": "HIGH",
    },
    {
        "company": "Ideogram",
        "website": "https://ideogram.ai",
        "linkedin": "https://linkedin.com/company/ideogram-ai",
        "category": "Image Generation",
        "relevance": "Text rendering, creative generation",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Photoroom",
        "website": "https://photoroom.com",
        "linkedin": "https://linkedin.com/company/photoroom",
        "category": "Image Generation",
        "relevance": "AI photo editing, background generation",
        "funding_stage": "Series B ($64M)",
        "country": "France",
        "priority": "MEDIUM",
    },
    {
        "company": "Artbreeder",
        "website": "https://artbreeder.com",
        "linkedin": "https://linkedin.com/company/artbreeder",
        "category": "Image Generation",
        "relevance": "Collaborative AI art, character portraits",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "NovelAI",
        "website": "https://novelai.net",
        "linkedin": "",
        "category": "Image Generation",
        "relevance": "Anime-focused image generation, storytelling",
        "funding_stage": "Unknown",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Invoke AI",
        "website": "https://invoke.com",
        "linkedin": "https://linkedin.com/company/invoke-ai",
        "category": "Image Generation",
        "relevance": "Open-source Stable Diffusion tools, acquired by Adobe",
        "funding_stage": "Acquired",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Krea AI",
        "website": "https://krea.ai",
        "linkedin": "https://linkedin.com/company/krea-ai",
        "category": "Image Generation",
        "relevance": "Real-time AI generation, creative tools",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Playgroundai",
        "website": "https://playground.com",
        "linkedin": "https://linkedin.com/company/playgroundai",
        "category": "Image Generation",
        "relevance": "Free AI image generation platform",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "NightCafe",
        "website": "https://nightcafe.studio",
        "linkedin": "https://linkedin.com/company/nightcafe-studio",
        "category": "Image Generation",
        "relevance": "AI art community, multiple models",
        "funding_stage": "Bootstrapped",
        "country": "Australia",
        "priority": "LOW",
    },
    {
        "company": "Civitai",
        "website": "https://civitai.com",
        "linkedin": "https://linkedin.com/company/civitai",
        "category": "Image Generation",
        "relevance": "AI model sharing platform, huge anime model community",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Tensor.Art",
        "website": "https://tensor.art",
        "linkedin": "",
        "category": "Image Generation",
        "relevance": "AI image generation, anime focus",
        "funding_stage": "Unknown",
        "country": "Singapore",
        "priority": "HIGH",
    },
    {
        "company": "PixAI",
        "website": "https://pixai.art",
        "linkedin": "",
        "category": "Image Generation",
        "relevance": "Anime-specific AI art generator",
        "funding_stage": "Unknown",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Holara AI",
        "website": "https://holara.ai",
        "linkedin": "",
        "category": "Image Generation",
        "relevance": "Anime art generation specialist",
        "funding_stage": "Unknown",
        "country": "US",
        "priority": "HIGH",
    },

    # === VIDEO GENERATION (12) ===
    {
        "company": "Runway",
        "website": "https://runwayml.com",
        "linkedin": "https://linkedin.com/company/runwayml",
        "category": "Video Generation",
        "relevance": "Gen-3 video, animation capabilities",
        "funding_stage": "Series D ($544M)",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Pika Labs",
        "website": "https://pika.art",
        "linkedin": "https://linkedin.com/company/pika-labs",
        "category": "Video Generation",
        "relevance": "Video generation from images/text",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Luma AI",
        "website": "https://lumalabs.ai",
        "linkedin": "https://linkedin.com/company/luma-ai",
        "category": "Video Generation",
        "relevance": "Dream Machine video generation",
        "funding_stage": "Series B",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "HeyGen",
        "website": "https://heygen.com",
        "linkedin": "https://linkedin.com/company/heygen",
        "category": "Video Generation",
        "relevance": "AI avatar video generation",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Haiper",
        "website": "https://haiper.ai",
        "linkedin": "https://linkedin.com/company/haiper-ai",
        "category": "Video Generation",
        "relevance": "Video generation, ex-DeepMind team",
        "funding_stage": "Series A",
        "country": "UK",
        "priority": "HIGH",
    },
    {
        "company": "Kling AI (Kuaishou)",
        "website": "https://klingai.com",
        "linkedin": "https://linkedin.com/company/kuaishou",
        "category": "Video Generation",
        "relevance": "Top-ranked video generation, entertainment focus",
        "funding_stage": "Corporate",
        "country": "China",
        "priority": "HIGH",
    },
    {
        "company": "Minimax",
        "website": "https://minimaxi.com",
        "linkedin": "https://linkedin.com/company/minimax-ai",
        "category": "Video Generation",
        "relevance": "Hailuo video, $2.5B valuation",
        "funding_stage": "Series B",
        "country": "China",
        "priority": "HIGH",
    },
    {
        "company": "Captions",
        "website": "https://captions.ai",
        "linkedin": "https://linkedin.com/company/captions-ai",
        "category": "Video Generation",
        "relevance": "AI video editing, avatars for creators",
        "funding_stage": "Series C ($100M)",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "D-ID",
        "website": "https://d-id.com",
        "linkedin": "https://linkedin.com/company/d-id",
        "category": "Video Generation",
        "relevance": "AI video avatars, talking heads",
        "funding_stage": "Series B",
        "country": "Israel",
        "priority": "MEDIUM",
    },
    {
        "company": "Hedra",
        "website": "https://hedra.com",
        "linkedin": "https://linkedin.com/company/hedra-ai",
        "category": "Video Generation",
        "relevance": "Character dialogue videos, $32M from A16z",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Veo (Google DeepMind)",
        "website": "https://deepmind.google",
        "linkedin": "https://linkedin.com/company/googledeepmind",
        "category": "Video Generation",
        "relevance": "Google's video generation model",
        "funding_stage": "Corporate",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Zhipu AI (Ying)",
        "website": "https://zhipuai.cn",
        "linkedin": "",
        "category": "Video Generation",
        "relevance": "Chinese video generation, Sora competitor",
        "funding_stage": "Series C",
        "country": "China",
        "priority": "MEDIUM",
    },

    # === GAMING AI (15) ===
    {
        "company": "Inworld AI",
        "website": "https://inworld.ai",
        "linkedin": "https://linkedin.com/company/inworld-ai",
        "category": "Gaming AI",
        "relevance": "NPC AI, Xbox/Microsoft partnership",
        "funding_stage": "Series A ($60M)",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Convai",
        "website": "https://convai.com",
        "linkedin": "https://linkedin.com/company/convai",
        "category": "Gaming AI",
        "relevance": "Game character conversations",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Scenario",
        "website": "https://scenario.com",
        "linkedin": "https://linkedin.com/company/scenario-gg",
        "category": "Gaming AI",
        "relevance": "AI game asset generation",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Sett",
        "website": "https://sett.gg",
        "linkedin": "https://linkedin.com/company/sett-ai",
        "category": "Gaming AI",
        "relevance": "AI agents for mobile game dev, $27M funding",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Layer AI",
        "website": "https://layer.ai",
        "linkedin": "https://linkedin.com/company/layer-ai",
        "category": "Gaming AI",
        "relevance": "AI game asset creation platform",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Latitude (AI Dungeon)",
        "website": "https://latitude.io",
        "linkedin": "https://linkedin.com/company/latitude-io",
        "category": "Gaming AI",
        "relevance": "AI-powered interactive storytelling",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Promethean AI",
        "website": "https://prometheanai.com",
        "linkedin": "https://linkedin.com/company/promethean-ai",
        "category": "Gaming AI",
        "relevance": "AI virtual world creation",
        "funding_stage": "Seed ($3.5M)",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Blackshark AI",
        "website": "https://blackshark.ai",
        "linkedin": "https://linkedin.com/company/blackshark-ai",
        "category": "Gaming AI",
        "relevance": "3D world generation, Microsoft Flight Sim",
        "funding_stage": "Series B",
        "country": "Austria",
        "priority": "MEDIUM",
    },
    {
        "company": "Roblox",
        "website": "https://roblox.com",
        "linkedin": "https://linkedin.com/company/roblox",
        "category": "Gaming AI",
        "relevance": "AI game creation tools, massive platform",
        "funding_stage": "Public",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Unity",
        "website": "https://unity.com",
        "linkedin": "https://linkedin.com/company/unity-technologies",
        "category": "Gaming AI",
        "relevance": "Game engine with AI tools",
        "funding_stage": "Public",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Sortium",
        "website": "https://sortium.com",
        "linkedin": "https://linkedin.com/company/sortium",
        "category": "Gaming AI",
        "relevance": "Real-time 3D asset generation",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Opus",
        "website": "https://opus.ai",
        "linkedin": "https://linkedin.com/company/opus-ai",
        "category": "Gaming AI",
        "relevance": "Generative AI world building",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Spline",
        "website": "https://spline.design",
        "linkedin": "https://linkedin.com/company/splonetool",
        "category": "Gaming AI",
        "relevance": "3D design with AI generation",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Ponzu",
        "website": "https://ponzu.ai",
        "linkedin": "",
        "category": "Gaming AI",
        "relevance": "AI texturing for 3D assets",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Meshy",
        "website": "https://meshy.ai",
        "linkedin": "https://linkedin.com/company/meshy-ai",
        "category": "Gaming AI",
        "relevance": "3D model generation from text/images",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
    },

    # === ANIMATION AI (10) ===
    {
        "company": "Cartwheel",
        "website": "https://cartwheel.com",
        "linkedin": "https://linkedin.com/company/cartwheel-ai",
        "category": "Animation AI",
        "relevance": "3D character animation, Pixar/DreamWorks users",
        "funding_stage": "Seed ($15.6M)",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Cheehoo",
        "website": "https://cheehoo.ai",
        "linkedin": "https://linkedin.com/company/cheehoo-ai",
        "category": "Animation AI",
        "relevance": "Animation AI, ex-DreamWorks team",
        "funding_stage": "Seed ($10M)",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Animation Inc.",
        "website": "https://animation.inc",
        "linkedin": "https://linkedin.com/company/animation-inc",
        "category": "Animation AI",
        "relevance": "Real-time generative animation",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Kinetix",
        "website": "https://kinetix.tech",
        "linkedin": "https://linkedin.com/company/kinetix",
        "category": "Animation AI",
        "relevance": "AI motion capture for games",
        "funding_stage": "Series A",
        "country": "France",
        "priority": "HIGH",
    },
    {
        "company": "Wonder Dynamics",
        "website": "https://wonderdynamics.com",
        "linkedin": "https://linkedin.com/company/wonder-dynamics",
        "category": "Animation AI",
        "relevance": "AI-powered VFX, acquired by Autodesk",
        "funding_stage": "Acquired",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Plask",
        "website": "https://plask.ai",
        "linkedin": "https://linkedin.com/company/plask-ai",
        "category": "Animation AI",
        "relevance": "AI motion capture from video",
        "funding_stage": "Series A",
        "country": "South Korea",
        "priority": "HIGH",
    },
    {
        "company": "Kaedim",
        "website": "https://kaedim3d.com",
        "linkedin": "https://linkedin.com/company/kaedim",
        "category": "Animation AI",
        "relevance": "2D to 3D AI conversion",
        "funding_stage": "Series A",
        "country": "UK",
        "priority": "HIGH",
    },
    {
        "company": "Rokoko",
        "website": "https://rokoko.com",
        "linkedin": "https://linkedin.com/company/rokoko-electronics",
        "category": "Animation AI",
        "relevance": "Motion capture, AI-assisted animation",
        "funding_stage": "Series A",
        "country": "Denmark",
        "priority": "MEDIUM",
    },
    {
        "company": "DeepMotion",
        "website": "https://deepmotion.com",
        "linkedin": "https://linkedin.com/company/deepmotion",
        "category": "Animation AI",
        "relevance": "AI body tracking and animation",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "RADiCAL",
        "website": "https://radical.app",
        "linkedin": "https://linkedin.com/company/radical-motion",
        "category": "Animation AI",
        "relevance": "AI motion capture from video",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "MEDIUM",
    },

    # === CHARACTER/AVATAR AI (10) ===
    {
        "company": "Character.AI",
        "website": "https://character.ai",
        "linkedin": "https://linkedin.com/company/character-ai",
        "category": "Character AI",
        "relevance": "AI characters, personality generation",
        "funding_stage": "Series A ($150M)",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Synthesia",
        "website": "https://synthesia.io",
        "linkedin": "https://linkedin.com/company/synthesiahq",
        "category": "Character AI",
        "relevance": "AI video avatars, $2.1B valuation",
        "funding_stage": "Series D ($180M)",
        "country": "UK",
        "priority": "MEDIUM",
    },
    {
        "company": "Soul Machines",
        "website": "https://soulmachines.com",
        "linkedin": "https://linkedin.com/company/soul-machines",
        "category": "Character AI",
        "relevance": "Autonomous digital humans",
        "funding_stage": "Series B",
        "country": "New Zealand",
        "priority": "MEDIUM",
    },
    {
        "company": "Genies",
        "website": "https://genies.com",
        "linkedin": "https://linkedin.com/company/genaborhood",
        "category": "Character AI",
        "relevance": "AI avatar creation platform",
        "funding_stage": "Series C",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Lemon Slice",
        "website": "https://lemonslice.ai",
        "linkedin": "https://linkedin.com/company/lemon-slice-ai",
        "category": "Character AI",
        "relevance": "Real-time AI avatars, $10.5M from YC",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "AvatarOS",
        "website": "https://avatar.os",
        "linkedin": "https://linkedin.com/company/avataros",
        "category": "Character AI",
        "relevance": "Virtual influencer platform, A16z backed",
        "funding_stage": "Seed ($7M)",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Hologram Labs",
        "website": "https://hologramlabs.com",
        "linkedin": "https://linkedin.com/company/hologram-labs",
        "category": "Character AI",
        "relevance": "AI for vtubers/digital celebrities",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "IMVU",
        "website": "https://imvu.com",
        "linkedin": "https://linkedin.com/company/imvu",
        "category": "Character AI",
        "relevance": "Avatar social platform with AI",
        "funding_stage": "Growth",
        "country": "US",
        "priority": "LOW",
    },
    {
        "company": "Ready Player Me",
        "website": "https://readyplayer.me",
        "linkedin": "https://linkedin.com/company/wolf3d",
        "category": "Character AI",
        "relevance": "Cross-game avatar platform",
        "funding_stage": "Series B",
        "country": "Estonia",
        "priority": "MEDIUM",
    },
    {
        "company": "Uneeq",
        "website": "https://uneeq.com",
        "linkedin": "https://linkedin.com/company/uneeq",
        "category": "Character AI",
        "relevance": "Digital human platform",
        "funding_stage": "Series A",
        "country": "New Zealand",
        "priority": "MEDIUM",
    },

    # === VOICE AI (8) ===
    {
        "company": "ElevenLabs",
        "website": "https://elevenlabs.io",
        "linkedin": "https://linkedin.com/company/elevenlabsio",
        "category": "Voice AI",
        "relevance": "Voice synthesis for characters, $3.3B valuation",
        "funding_stage": "Series C ($180M)",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Resemble AI",
        "website": "https://resemble.ai",
        "linkedin": "https://linkedin.com/company/resembleai",
        "category": "Voice AI",
        "relevance": "Voice cloning for games/content",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Replica Studios",
        "website": "https://replicastudios.com",
        "linkedin": "https://linkedin.com/company/replica-studios",
        "category": "Voice AI",
        "relevance": "AI voices for games",
        "funding_stage": "Series A",
        "country": "Australia",
        "priority": "HIGH",
    },
    {
        "company": "WellSaid Labs",
        "website": "https://wellsaidlabs.com",
        "linkedin": "https://linkedin.com/company/wellsaid-labs",
        "category": "Voice AI",
        "relevance": "Enterprise AI voice platform",
        "funding_stage": "Series B",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Murf AI",
        "website": "https://murf.ai",
        "linkedin": "https://linkedin.com/company/murf-ai",
        "category": "Voice AI",
        "relevance": "Text-to-speech for creators",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Play.ht",
        "website": "https://play.ht",
        "linkedin": "https://linkedin.com/company/play-ht",
        "category": "Voice AI",
        "relevance": "AI voice generation platform",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Suno",
        "website": "https://suno.ai",
        "linkedin": "https://linkedin.com/company/suno-ai",
        "category": "Voice AI",
        "relevance": "AI music generation, $125M Series B",
        "funding_stage": "Series B ($125M)",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Udio",
        "website": "https://udio.com",
        "linkedin": "https://linkedin.com/company/udio-ai",
        "category": "Voice AI",
        "relevance": "AI music generation",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
    },

    # === DATA/TRAINING (10) ===
    {
        "company": "Scale AI",
        "website": "https://scale.com",
        "linkedin": "https://linkedin.com/company/scale-ai",
        "category": "Training Data",
        "relevance": "Training data for AI, $7.3B valuation",
        "funding_stage": "Series E",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Labelbox",
        "website": "https://labelbox.com",
        "linkedin": "https://linkedin.com/company/labelbox",
        "category": "Training Data",
        "relevance": "Data labeling platform",
        "funding_stage": "Series D",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Gretel AI",
        "website": "https://gretel.ai",
        "linkedin": "https://linkedin.com/company/gretel-ai",
        "category": "Training Data",
        "relevance": "Synthetic data generation, $65.5M funding",
        "funding_stage": "Series B",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Synthesis AI",
        "website": "https://synthesis.ai",
        "linkedin": "https://linkedin.com/company/synthesisai",
        "category": "Training Data",
        "relevance": "Synthetic data for computer vision",
        "funding_stage": "Series B ($30M)",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Tonic AI",
        "website": "https://tonic.ai",
        "linkedin": "https://linkedin.com/company/tonic-ai",
        "category": "Training Data",
        "relevance": "Synthetic data generation",
        "funding_stage": "Series C ($35M)",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Parallel Domain",
        "website": "https://paralleldomain.com",
        "linkedin": "https://linkedin.com/company/parallel-domain",
        "category": "Training Data",
        "relevance": "Synthetic data for perception AI",
        "funding_stage": "Series A ($22.5M)",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Surge AI",
        "website": "https://surgehq.ai",
        "linkedin": "https://linkedin.com/company/surge-ai",
        "category": "Training Data",
        "relevance": "High-quality AI training data",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Sama",
        "website": "https://sama.com",
        "linkedin": "https://linkedin.com/company/sama",
        "category": "Training Data",
        "relevance": "AI training data annotation",
        "funding_stage": "Series C",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Defined.ai",
        "website": "https://defined.ai",
        "linkedin": "https://linkedin.com/company/defined-ai",
        "category": "Training Data",
        "relevance": "AI data marketplace",
        "funding_stage": "Series B",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Mostly AI",
        "website": "https://mostly.ai",
        "linkedin": "https://linkedin.com/company/mostly-ai",
        "category": "Training Data",
        "relevance": "Synthetic data platform",
        "funding_stage": "Series B",
        "country": "Austria",
        "priority": "MEDIUM",
    },

    # === FOUNDATION MODELS (10) ===
    {
        "company": "OpenAI",
        "website": "https://openai.com",
        "linkedin": "https://linkedin.com/company/openai",
        "category": "Foundation Models",
        "relevance": "DALL-E, Sora - visual generation",
        "funding_stage": "Growth",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Anthropic",
        "website": "https://anthropic.com",
        "linkedin": "https://linkedin.com/company/anthropic",
        "category": "Foundation Models",
        "relevance": "Claude - multimodal capabilities",
        "funding_stage": "Series C+",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Mistral AI",
        "website": "https://mistral.ai",
        "linkedin": "https://linkedin.com/company/mistral-ai",
        "category": "Foundation Models",
        "relevance": "Open-weight models, multimodal",
        "funding_stage": "Series B",
        "country": "France",
        "priority": "MEDIUM",
    },
    {
        "company": "Cohere",
        "website": "https://cohere.com",
        "linkedin": "https://linkedin.com/company/cohere-ai",
        "category": "Foundation Models",
        "relevance": "Enterprise LLM platform",
        "funding_stage": "Series C",
        "country": "Canada",
        "priority": "LOW",
    },
    {
        "company": "AI21 Labs",
        "website": "https://ai21.com",
        "linkedin": "https://linkedin.com/company/ai21",
        "category": "Foundation Models",
        "relevance": "Jamba models, enterprise AI",
        "funding_stage": "Series C",
        "country": "Israel",
        "priority": "LOW",
    },
    {
        "company": "Moonshot AI (Kimi)",
        "website": "https://moonshot.cn",
        "linkedin": "",
        "category": "Foundation Models",
        "relevance": "Chinese foundation model, multimodal",
        "funding_stage": "Series B",
        "country": "China",
        "priority": "MEDIUM",
    },
    {
        "company": "01.AI",
        "website": "https://01.ai",
        "linkedin": "https://linkedin.com/company/01-ai",
        "category": "Foundation Models",
        "relevance": "Yi models, Kai-Fu Lee startup",
        "funding_stage": "Series A",
        "country": "China",
        "priority": "MEDIUM",
    },
    {
        "company": "Stepfun",
        "website": "https://stepfun.com",
        "linkedin": "",
        "category": "Foundation Models",
        "relevance": "Chinese AI startup, multimodal",
        "funding_stage": "Series B",
        "country": "China",
        "priority": "LOW",
    },
    {
        "company": "Baichuan",
        "website": "https://baichuan-ai.com",
        "linkedin": "",
        "category": "Foundation Models",
        "relevance": "Chinese LLM startup",
        "funding_stage": "Series A",
        "country": "China",
        "priority": "LOW",
    },
    {
        "company": "Alibaba (Tongyi)",
        "website": "https://tongyi.aliyun.com",
        "linkedin": "https://linkedin.com/company/alibaba",
        "category": "Foundation Models",
        "relevance": "Qwen models, Wan video generation",
        "funding_stage": "Corporate",
        "country": "China",
        "priority": "MEDIUM",
    },

    # === CREATIVE TOOLS (10) ===
    {
        "company": "Descript",
        "website": "https://descript.com",
        "linkedin": "https://linkedin.com/company/descript",
        "category": "Creative Tools",
        "relevance": "AI video/audio editing, Overdub voice",
        "funding_stage": "Series C ($100M)",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Canva",
        "website": "https://canva.com",
        "linkedin": "https://linkedin.com/company/canva",
        "category": "Creative Tools",
        "relevance": "Design platform with AI generation",
        "funding_stage": "Growth",
        "country": "Australia",
        "priority": "LOW",
    },
    {
        "company": "Jasper",
        "website": "https://jasper.ai",
        "linkedin": "https://linkedin.com/company/jasper-ai",
        "category": "Creative Tools",
        "relevance": "AI content platform",
        "funding_stage": "Series A",
        "country": "US",
        "priority": "LOW",
    },
    {
        "company": "Luma Labs",
        "website": "https://lumalabs.ai",
        "linkedin": "https://linkedin.com/company/luma-ai",
        "category": "Creative Tools",
        "relevance": "3D capture and generation",
        "funding_stage": "Series B",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Topaz Labs",
        "website": "https://topazlabs.com",
        "linkedin": "https://linkedin.com/company/topaz-labs",
        "category": "Creative Tools",
        "relevance": "AI image/video enhancement",
        "funding_stage": "Bootstrapped",
        "country": "US",
        "priority": "MEDIUM",
    },
    {
        "company": "Magnific AI",
        "website": "https://magnific.ai",
        "linkedin": "https://linkedin.com/company/magnific-ai",
        "category": "Creative Tools",
        "relevance": "AI image upscaling/enhancement",
        "funding_stage": "Seed",
        "country": "Spain",
        "priority": "HIGH",
    },
    {
        "company": "Clipdrop (Stability)",
        "website": "https://clipdrop.co",
        "linkedin": "https://linkedin.com/company/clipdrop",
        "category": "Creative Tools",
        "relevance": "AI image editing tools",
        "funding_stage": "Acquired",
        "country": "France",
        "priority": "MEDIUM",
    },
    {
        "company": "Imagen AI",
        "website": "https://imagen-ai.com",
        "linkedin": "https://linkedin.com/company/imagen-ai",
        "category": "Creative Tools",
        "relevance": "AI photo editing for photographers",
        "funding_stage": "Series A",
        "country": "Israel",
        "priority": "LOW",
    },
    {
        "company": "Kaiber",
        "website": "https://kaiber.ai",
        "linkedin": "https://linkedin.com/company/kaiber-ai",
        "category": "Creative Tools",
        "relevance": "AI video generation for creators",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
    },
    {
        "company": "Genmo",
        "website": "https://genmo.ai",
        "linkedin": "https://linkedin.com/company/genmo-ai",
        "category": "Creative Tools",
        "relevance": "AI video/3D generation",
        "funding_stage": "Seed",
        "country": "US",
        "priority": "HIGH",
    },
]


def generate_csv(output_path: str = "output/ai_companies_lead_list.csv"):
    """Generate CSV file for Attio/Apollo import."""
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)

    fieldnames = [
        "company",
        "website",
        "linkedin",
        "category",
        "relevance",
        "funding_stage",
        "country",
        "priority",
    ]

    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(LEAD_LIST)

    print(f"Generated {len(LEAD_LIST)} companies to {output_path}")
    return output_path


def get_high_priority():
    """Get HIGH priority leads only."""
    return [c for c in LEAD_LIST if c["priority"] == "HIGH"]


def get_by_category(category: str):
    """Filter by category."""
    return [c for c in LEAD_LIST if c["category"] == category]


def summary():
    """Print summary of the lead list."""
    print(f"\n{'='*60}")
    print("AI COMPANIES LEAD LIST SUMMARY")
    print(f"{'='*60}")
    print(f"Total companies: {len(LEAD_LIST)}")

    # By priority
    high = len([c for c in LEAD_LIST if c["priority"] == "HIGH"])
    med = len([c for c in LEAD_LIST if c["priority"] == "MEDIUM"])
    low = len([c for c in LEAD_LIST if c["priority"] == "LOW"])
    print(f"\nBy Priority:")
    print(f"  HIGH:   {high}")
    print(f"  MEDIUM: {med}")
    print(f"  LOW:    {low}")

    # By category
    categories = {}
    for c in LEAD_LIST:
        cat = c["category"]
        categories[cat] = categories.get(cat, 0) + 1

    print(f"\nBy Category:")
    for cat, count in sorted(categories.items(), key=lambda x: -x[1]):
        print(f"  {cat}: {count}")

    # By country
    countries = {}
    for c in LEAD_LIST:
        country = c["country"]
        countries[country] = countries.get(country, 0) + 1

    print(f"\nBy Country:")
    for country, count in sorted(countries.items(), key=lambda x: -x[1])[:5]:
        print(f"  {country}: {count}")


if __name__ == "__main__":
    summary()
    generate_csv()
